### PR TITLE
Add MSVC debugger visualization file

### PR DESCRIPTION
**Pull request by cmakshin**
This pull request contains a file which can be used by the Visual Studio debugger for "pretty-printing" `tsl::ordered_*` containers.

### CODE REVIEW

**Comment by Tessil** [comment]
Hello,

Thank you for your contribution.

I'm currently in holiday without my laptop for the next few weeks, so I can't really test it. I'll check to merge it on my return so that I can check and test it a bit more beforehand as I'm not familiar with the natvis files.

**Comment by cmakshin** [comment]
Hi Thibaut.

OK, the delay is not a problem.

Have nice holidays! :)

**Comment by Tessil** [comment]
Hello,

I made some minor changes to your branch. If it seems OK to you, I will merge the branch to the master.

**Comment by cmakshin** [comment]
Hi.

Looks good.

**Comment by Tessil** [comment]
I also hesitate to remove the `IncludeView="detailed"` in `bucket_count` and `max_load_factor`. Is there a reason to not leave them in the default view?

**Comment by cmakshin** [comment]
That's the behavior of the `std::unordered_map` visualizer shipped with MSVC and I tried to be as close to it as possible.

**Comment by Tessil** [comment]
Ok, makes sense. I merged the changes.

I'll check to merge the 'natvis' files in the other `tsl` projects when I have time.

**Pull request merged**
